title:              "ZE RECORD"
tagline:            "슬쩍 알아두면, 조금 더 즐거워지는 것들"
email:              "esdeloj@gmail.com"
description:        "마케터 ze가 기록하는 여행, 취향 그리고 일!"
author:             "ze"
baseurl:            "/"
url:                "https://nohze.com"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.jpg"

# # Social Profiles
# twitter_username:   twitter_username
# instagram_username: instagram_username
# facebook_username:  facebook_username
# linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# 블로그 disqus shortname
disqus:
  shortname: nohze-com
